### PR TITLE
feat(ci): add `pre-commit`

### PR DESCRIPTION
**Pull request by JaeAeich**
Add precommit, initialize it with necessary checks to keep code change abide by a standard. 

Please look at `.pre-commit.config` for all the hooks that are added. 
 
For reviewer's sake, listing some config that have changed alot of files:
- [mdformat](https://mdformat.readthedocs.io/en/stable/index.html), restricting the line length auto fixed multiple files.
- [toml-sort](https://github.com/pappasam/toml-sort), sorted all toml files alphabetically.
- [trailing-whitespaces](https://pre-commit.com/hooks.html#:~:text=trailing%2Dwhitespace%20%2D%20trims%20trailing%20whitespace.)
- [end-of-file-fixer](https://pre-commit.com/hooks.html#:~:text=end%2Dof%2Dfile%2Dfixer%20%2D%20ensures%20that%20a%20file%20is%20either%20empty%2C%20or%20ends%20with%20one%20newline)

Note: This introduces a discrepancy in the checks between CI and pre-commit, it won't be hard (if someone wanted to) bypass precommit checks and push the code changes. Given adding all the hooks to CI as well might slow CI down, I thinks this discrepancy is the sweet spot. CI has checks for very absolutely necessary checks and pre-commit has some necessary and many nice-to-have checks.

EDIT: THIS `pre-commit` IS JUST FOR CI, NOT ADDED AS A `git` HOOK.

### CODE REVIEW

**Comment by uniqueg** [comment]
Thanks @JaeAeich. I'm actually not so sure about having different checks for the pre-commit hook and the CI. Either we really care about things (and then we should enforce them, through the CI), or we don't (then why bother people at all?). Which is why I never ran with committing pre-commit checks at all and just do them for myself to save time on the overhead of CI checks. Thus, I would actually prefer to match the actual requirements across CI and hooks (minus long-running tests or tests that are difficult to run local). Would we really want to rely on users setting up the hooks to avoid spelling mistakes (which are hard to find even during reviews)?

Btw, given our work mode where we squash merge, I think using a pre-push hook would be more appropriate. We allow feature branches to be messy, so no need to raise the bar for people to commit. For example, I sometimes commit and don't push when I feel I have reached a milestone, either because I feel that it's a commit that what really stand on its own, or just because I want or need to store my current work to check out some other branch. Sure, I could just skip the hook, but given that commits on feature branches aren't really the units we care about, I think the more natural timepoint to run checks in this flow would be prior to pushin.

**Comment by JaeAeich** [comment]
@uniqueg Yeah makes sense (thats what happened in cloud-component lol, thats why I wrote the PS in desc), on that note I have remove pre-commit as a git hook but left it in the CI, as `General checks` in `PR Evaluation`, if you think thats not an overkill, merge #182 and then this. On the other hand if it feels like an overkill and these files should be time linted by dev on their own, thats also fine, please feel free to close this PR :).

**Comment by uniqueg** [comment]
Let's leave it open for now and see which of these checks might be worth including in the CI, because I think there are certainly some.

**Comment by uniqueg** [comment]
Closing for now - can still be used as reference for CI future updates

**Pull request closed without merging**
