### PR TITLE
chore(docs): run sphinx-apidocs

### PR DESCRIPTION
**Pull request by JaeAeich**
## Summary by Sourcery

Enhance documentation formatting and readability, add resource limits and security context configurations to Kubernetes templates, update ingress configuration to 'networking.k8s.io/v1', and introduce new unit tests, OpenAPI specification, Python models, Kubernetes client wrapper, taskmaster script, and example input JSON file.

Enhancements:
- Update documentation formatting in 'local_ftp.md' and 'README.md' for better readability and consistency.
- Add resource limits and security context configurations to the Kubernetes deployment templates.
- Update Kubernetes ingress configuration to use the 'networking.k8s.io/v1' API version.

Documentation:
- Add badges to 'README.md' for code coverage, documentation status, license, Python version, development status, contributors, and security tools.
- Update 'README.md' to improve structure and readability, including better formatting and links.

Tests:
- Add unit tests for the 'Job' class in 'tests/test_unit/test_services/test_job.py'.

Chores:
- Add OpenAPI specification file 'task_execution_service.117cd92.openapi.yaml' for the Task Execution Service API.
- Add new Python models for the TES API in 'tesk/api/ga4gh/tes/models.py'.
- Add new Kubernetes client wrapper in 'tesk/api/kubernetes/wrapper.py'.
- Add new taskmaster script in 'tesk/services/taskmaster.py'.
- Add example input JSON file 'docs/examples/inputHelloWorld.json'.

### CODE REVIEW

**Comment by JaeAeich** [comment]
#201 should be merged first.

**Review by uniqueg — COMMENTED** [review]
I suppose if you remove all the changes in the `tesk` package, this PR will probably be good to go once the other stuff is merged, which - as you say - should happen first.

**Review by uniqueg — COMMENTED** [review]
The docs stuff looks fine, but not sure why there are the other files (constants, wrapper, exceptions) in this PR. Just remove it. Then, when #201 is merged, you can merge `main` into this feature branch and all will be fine.

Also, not sure about the PR title: I don't see any code that runs the API docs build, but rather only changes to the pages. So shouldn't it be something like `docs: add API docs pages` or `docs: extend API docs` or something like that?

**Comment by JaeAeich** [comment]
closing as #201 got this covered.

**Pull request closed without merging**
